services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    env_file:
      - ./apps/server/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: