services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    env_file:
      - ./apps/server/.env
    # Remove port mapping in production
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: